import type { DiagnosticQuestion } from './types';

// Original diagnostic items written for this project. They are not ETS questions.
export const baselineQuestions: readonly DiagnosticQuestion[] = [
  { id:'p5-001', domain:'reading', part:5, skill:'parts_of_speech', prompt:'The marketing team responded _____ to the sudden increase in customer inquiries.', choices:['prompt','promptly','promptness','prompting'], correctAnswer:1, explanation:'The verb “responded” is modified by the adverb “promptly”.' },
  { id:'p5-002', domain:'reading', part:5, skill:'agreement', prompt:'Each of the regional offices _____ its sales report by Friday afternoon.', choices:['submit','submits','submitting','have submitted'], correctAnswer:1, explanation:'The subject “Each” is singular, so “submits” agrees with it.' },
  { id:'p5-003', domain:'reading', part:5, skill:'prepositions', prompt:'The conference room will remain unavailable _____ noon because of maintenance.', choices:['until','during','among','beside'], correctAnswer:0, explanation:'“Until” marks the endpoint of the period of unavailability.' },
  { id:'p5-004', domain:'reading', part:5, skill:'tense', prompt:'By the time the auditors arrive tomorrow, the finance department _____ the records.', choices:['prepares','prepared','will have prepared','has prepared'], correctAnswer:2, explanation:'Future perfect fits an action completed before another future event.' },
  { id:'p5-005', domain:'reading', part:5, skill:'connectors', prompt:'_____ the shipment was delayed, the retailer informed customers immediately.', choices:['Although','Despite','Because of','In spite'], correctAnswer:0, explanation:'“Although” can introduce the full clause “the shipment was delayed”.' },
  { id:'p5-006', domain:'reading', part:5, skill:'collocations', prompt:'Applicants are asked to _____ a copy of their identification with the form.', choices:['attach','combine','join','stick'], correctAnswer:0, explanation:'“Attach a copy/document” is the natural workplace collocation here.' },
  { id:'p5-007', domain:'reading', part:5, skill:'pronouns', prompt:'Ms. Patel thanked the volunteers for _____ assistance during the event.', choices:['they','them','their','theirs'], correctAnswer:2, explanation:'A possessive determiner is required before the noun “assistance”.' },
  { id:'p5-008', domain:'reading', part:5, skill:'word_form', prompt:'The new scheduling system has improved the _____ of the support team.', choices:['efficient','efficiently','efficiency','efficiencies'], correctAnswer:2, explanation:'The noun “efficiency” is required after “the”.' },
  { id:'p5-009', domain:'reading', part:5, skill:'conditional', prompt:'If the supplier confirms the order today, we _____ the materials on Monday.', choices:['receive','received','will receive','would receive'], correctAnswer:2, explanation:'This is a real future condition: if + present, then will + base verb.' },
  { id:'p5-010', domain:'reading', part:5, skill:'relative_clauses', prompt:'The consultant _____ presented the proposal will lead the implementation team.', choices:['who','whose','which','where'], correctAnswer:0, explanation:'“Who” refers to a person and acts as the subject of “presented”.' },
  { id:'p6-001', domain:'reading', part:6, skill:'cohesion', prompt:'A store notice first explains that the entrance is being renovated. Which sentence best follows?', choices:['Customers should use the east-side entrance until the work is completed.','The company was founded more than thirty years ago.','Several employees attended a training seminar last month.','The catalog contains products in multiple colors.'], correctAnswer:0, explanation:'The first choice maintains the topic and gives a logical consequence/instruction.' },
  { id:'p6-002', domain:'reading', part:6, skill:'reference', prompt:'“The updated policy is attached to this message. Please review it before Friday.” What does “it” refer to?', choices:['Friday','the message','the updated policy','the attachment process'], correctAnswer:2, explanation:'The singular pronoun “it” refers back to “The updated policy”.' },
  { id:'p7-001', domain:'reading', part:7, skill:'detail_retrieval', prompt:'Email: “Your interview has been moved from 10:00 A.M. to 11:30 A.M. on Tuesday. Please check in at reception ten minutes early.” When should the applicant check in?', choices:['9:50 A.M.','10:50 A.M.','11:20 A.M.','11:30 A.M.'], correctAnswer:2, explanation:'Ten minutes before the revised 11:30 A.M. interview is 11:20 A.M.' },
  { id:'p7-002', domain:'reading', part:7, skill:'purpose', prompt:'Notice: “To reduce waiting time, customers may now book service appointments through our website.” What is the main purpose of the notice?', choices:['To announce a new booking option','To advertise a new product','To request customer feedback','To explain a price increase'], correctAnswer:0, explanation:'The notice announces that website appointment booking is now available.' },
  { id:'p7-003', domain:'reading', part:7, skill:'inference', prompt:'Memo: “The printer on the third floor will be replaced this afternoon. Until installation is complete, please send large print jobs to the second floor.” What can be inferred?', choices:['The second-floor printer can handle print jobs.','All printing is prohibited today.','The third floor is closed.','Employees must print from home.'], correctAnswer:0, explanation:'The instruction implies that the second-floor printer is available for those jobs.' },
  { id:'p7-004', domain:'reading', part:7, skill:'paraphrase', prompt:'“Complimentary parking is available to hotel guests.” Which sentence expresses the same idea?', choices:['Guests can park without paying.','Guests must reserve parking in advance.','Parking is limited to hotel employees.','Parking fees are paid at checkout.'], correctAnswer:0, explanation:'“Complimentary” means provided free of charge.' },
] as const;
